### ISSUE TITLE
A error related with mon_type

### ISSUE THREAD

**Issue by shinoratsutomu** [jhayes14/k-FP#2]
I have a issue like below in step 2.
This error occurred both mon_type is alexa and hs.
And also occurred in step 3.

Could you tell me the cause if this problem?

 - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
> python k-FP.py --RF_closedworld --mon_type alexa

C:\Python27\lib\site-packages\sklearn\cross_validation.py:41: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)
Traceback (most recent call last):
  File "k-FP.py", line 387, in <module>
    RF_closedworld(mon_type)
  File "k-FP.py", line 204, in RF_closedworld
    training, test = mon_train_test_references(mon_type, path_to_dict)
  File "k-FP.py", line 135, in mon_train_test_references
    dic = dill.load(fileObject1)
  File "C:\Python27\lib\site-packages\dill\dill.py", line 288, in load
    obj = pik.load()
  File "C:\Python27\lib\pickle.py", line 864, in load
    dispatch[key](self)
  File "C:\Python27\lib\pickle.py", line 1175, in load_binput
    i = ord(self.read(1))
TypeError: ord() expected a character, but string of length 0 found

 - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

**Comment by jhayes14** [comment]
Can you confirm you are reading the datasets correctly?

**Comment by shinoratsutomu** [comment]
Thanks hayes.
I finally managed this problem with Ubuntu OS.
Maybe my windows can't handle Features file.
